//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sarcophagy")]
        public string W1 {
            get {
                return ((string)(this["W1"]));
            }
            set {
                this["W1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zoophilist")]
        public string W2 {
            get {
                return ((string)(this["W2"]));
            }
            set {
                this["W2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monography")]
        public string W3 {
            get {
                return ((string)(this["W3"]));
            }
            set {
                this["W3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Loggerhead")]
        public string W4 {
            get {
                return ((string)(this["W4"]));
            }
            set {
                this["W4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lithoglyph")]
        public string W5 {
            get {
                return ((string)(this["W5"]));
            }
            set {
                this["W5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chromotype")]
        public string W6 {
            get {
                return ((string)(this["W6"]));
            }
            set {
                this["W6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cephalalgy")]
        public string W7 {
            get {
                return ((string)(this["W7"]));
            }
            set {
                this["W7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pantamorph")]
        public string W8 {
            get {
                return ((string)(this["W8"]));
            }
            set {
                this["W8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Smaragdite")]
        public string W9 {
            get {
                return ((string)(this["W9"]));
            }
            set {
                this["W9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spurgewort")]
        public string W10 {
            get {
                return ((string)(this["W10"]));
            }
            set {
                this["W10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : The practice of eating flesh")]
        public string C1 {
            get {
                return ((string)(this["C1"]));
            }
            set {
                this["C1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : A lover of animals")]
        public string C2 {
            get {
                return ((string)(this["C2"]));
            }
            set {
                this["C2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : Representation by lines without color")]
        public string C3 {
            get {
                return ((string)(this["C3"]));
            }
            set {
                this["C3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : A spherical mass of iron, with a long handle, used to heat tar")]
        public string C4 {
            get {
                return ((string)(this["C4"]));
            }
            set {
                this["C4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : An engraving on a gem")]
        public string C5 {
            get {
                return ((string)(this["C5"]));
            }
            set {
                this["C5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : A photographic picture in the natural colors")]
        public string C6 {
            get {
                return ((string)(this["C6"]));
            }
            set {
                this["C6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : Pain in the head; headache")]
        public string C7 {
            get {
                return ((string)(this["C7"]));
            }
            set {
                this["C7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : That which assumes, or exists in, all forms")]
        public string C8 {
            get {
                return ((string)(this["C8"]));
            }
            set {
                this["C8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : A green foliated kind of amphibole, observed in eclogite and some varietis" +
            " of gabbro")]
        public string C9 {
            get {
                return ((string)(this["C9"]));
            }
            set {
                this["C9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Clue : Any euphorbiaceous plant")]
        public string C10 {
            get {
                return ((string)(this["C10"]));
            }
            set {
                this["C10"] = value;
            }
        }
    }
}
